apiVersion: v1
kind: Service
metadata:
  name: fokus
  namespace: fokus
  labels:
    app: fokus
spec:
  type: NodePort
  metadata:
    labels:
      app: fokus
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: fokus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fokus
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - fokus
  selector:
    matchLabels:
      app: fokus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fokus
  namespace: fokus
spec:
  selector:
    matchLabels:
      app: fokus
  replicas: 1
  template:
    metadata:
      labels:
        app: fokus
    spec:
      containers:
        - name: fokus
          image: registry.brotherlogic-backend.com/brotherlogic/fokus:0.79.0 # {"$imagepolicy": "flux-system:fokus"}
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
