apiVersion: v1
kind: Service
metadata:
  name: habridge
  namespace: habridge
  labels:
    app: habridge
spec:
  type: NodePort
  metadata:
    labels:
      app: habridge
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: habridge
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: habridge
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - habridge
  selector:
    matchLabels:
      app: habridge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: habridge
  namespace: habridge
spec:
  selector:
    matchLabels:
      app: habridge
  replicas: 1
  template:
    metadata:
      labels:
        app: habridge
    spec:
      containers:
        - name: habridge
          image: registry.brotherlogic-backend.com/brotherlogic/habridge:0.15.0 # {"$imagepolicy": "flux-system:habridge"}
          ports:
            - containerPort: 8080
          env:
            - name: HA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hatoken
                  key: hatoken
            - name: HA_URL
              value: "homeassistant:8123"
      imagePullSecrets:
        - name: regcred
