// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: habridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateResponse_ButtonState int32

const (
	GetStateResponse_BUTTON_STATE_UNKNONW     GetStateResponse_ButtonState = 0
	GetStateResponse_BUTTON_STATE_UNAVAILABLE GetStateResponse_ButtonState = 1
	GetStateResponse_BUTTON_STATE_OFF         GetStateResponse_ButtonState = 2
	GetStateResponse_BUTTON_STATE_ON          GetStateResponse_ButtonState = 3
)

// Enum value maps for GetStateResponse_ButtonState.
var (
	GetStateResponse_ButtonState_name = map[int32]string{
		0: "BUTTON_STATE_UNKNONW",
		1: "BUTTON_STATE_UNAVAILABLE",
		2: "BUTTON_STATE_OFF",
		3: "BUTTON_STATE_ON",
	}
	GetStateResponse_ButtonState_value = map[string]int32{
		"BUTTON_STATE_UNKNONW":     0,
		"BUTTON_STATE_UNAVAILABLE": 1,
		"BUTTON_STATE_OFF":         2,
		"BUTTON_STATE_ON":          3,
	}
)

func (x GetStateResponse_ButtonState) Enum() *GetStateResponse_ButtonState {
	p := new(GetStateResponse_ButtonState)
	*p = x
	return p
}

func (x GetStateResponse_ButtonState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetStateResponse_ButtonState) Descriptor() protoreflect.EnumDescriptor {
	return file_habridge_proto_enumTypes[0].Descriptor()
}

func (GetStateResponse_ButtonState) Type() protoreflect.EnumType {
	return &file_habridge_proto_enumTypes[0]
}

func (x GetStateResponse_ButtonState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetStateResponse_ButtonState.Descriptor instead.
func (GetStateResponse_ButtonState) EnumDescriptor() ([]byte, []int) {
	return file_habridge_proto_rawDescGZIP(), []int{1, 0}
}

type GetStateResponse_UserState int32

const (
	GetStateResponse_USER_STATE_UNKNOWN GetStateResponse_UserState = 0
	GetStateResponse_USER_STATE_HOME    GetStateResponse_UserState = 1
	GetStateResponse_USER_STATE_AWAY    GetStateResponse_UserState = 2
)

// Enum value maps for GetStateResponse_UserState.
var (
	GetStateResponse_UserState_name = map[int32]string{
		0: "USER_STATE_UNKNOWN",
		1: "USER_STATE_HOME",
		2: "USER_STATE_AWAY",
	}
	GetStateResponse_UserState_value = map[string]int32{
		"USER_STATE_UNKNOWN": 0,
		"USER_STATE_HOME":    1,
		"USER_STATE_AWAY":    2,
	}
)

func (x GetStateResponse_UserState) Enum() *GetStateResponse_UserState {
	p := new(GetStateResponse_UserState)
	*p = x
	return p
}

func (x GetStateResponse_UserState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetStateResponse_UserState) Descriptor() protoreflect.EnumDescriptor {
	return file_habridge_proto_enumTypes[1].Descriptor()
}

func (GetStateResponse_UserState) Type() protoreflect.EnumType {
	return &file_habridge_proto_enumTypes[1]
}

func (x GetStateResponse_UserState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetStateResponse_UserState.Descriptor instead.
func (GetStateResponse_UserState) EnumDescriptor() ([]byte, []int) {
	return file_habridge_proto_rawDescGZIP(), []int{1, 1}
}

type GetStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ButtonId string `protobuf:"bytes,1,opt,name=button_id,json=buttonId,proto3" json:"button_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_habridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_habridge_proto_rawDescGZIP(), []int{0}
}

func (x *GetStateRequest) GetButtonId() string {
	if x != nil {
		return x.ButtonId
	}
	return ""
}

func (x *GetStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ButtonState GetStateResponse_ButtonState `protobuf:"varint,1,opt,name=button_state,json=buttonState,proto3,enum=habridge.GetStateResponse_ButtonState" json:"button_state,omitempty"`
	UserState   GetStateResponse_UserState   `protobuf:"varint,2,opt,name=user_state,json=userState,proto3,enum=habridge.GetStateResponse_UserState" json:"user_state,omitempty"`
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_habridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_habridge_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateResponse) GetButtonState() GetStateResponse_ButtonState {
	if x != nil {
		return x.ButtonState
	}
	return GetStateResponse_BUTTON_STATE_UNKNONW
}

func (x *GetStateResponse) GetUserState() GetStateResponse_UserState {
	if x != nil {
		return x.UserState
	}
	return GetStateResponse_USER_STATE_UNKNOWN
}

var File_habridge_proto protoreflect.FileDescriptor

var file_habridge_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x61, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x68, 0x61, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x22, 0x47, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0xe3, 0x02, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x62, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26,
	0x2e, 0x68, 0x61, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x68, 0x61, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x70, 0x0a, 0x0b, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x55, 0x54, 0x54, 0x4f,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x4e, 0x57, 0x10,
	0x00, 0x12, 0x1c, 0x0a, 0x18, 0x42, 0x55, 0x54, 0x54, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x14, 0x0a, 0x10, 0x42, 0x55, 0x54, 0x54, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x4f, 0x46, 0x46, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x42, 0x55, 0x54, 0x54, 0x4f, 0x4e, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x4e, 0x10, 0x03, 0x22, 0x4d, 0x0a, 0x09, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x48, 0x4f,
	0x4d, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x41, 0x57, 0x41, 0x59, 0x10, 0x02, 0x32, 0x54, 0x0a, 0x0f, 0x48, 0x61, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x68, 0x61, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x61, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x68, 0x61, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_habridge_proto_rawDescOnce sync.Once
	file_habridge_proto_rawDescData = file_habridge_proto_rawDesc
)

func file_habridge_proto_rawDescGZIP() []byte {
	file_habridge_proto_rawDescOnce.Do(func() {
		file_habridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_habridge_proto_rawDescData)
	})
	return file_habridge_proto_rawDescData
}

var file_habridge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_habridge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_habridge_proto_goTypes = []interface{}{
	(GetStateResponse_ButtonState)(0), // 0: habridge.GetStateResponse.ButtonState
	(GetStateResponse_UserState)(0),   // 1: habridge.GetStateResponse.UserState
	(*GetStateRequest)(nil),           // 2: habridge.GetStateRequest
	(*GetStateResponse)(nil),          // 3: habridge.GetStateResponse
}
var file_habridge_proto_depIdxs = []int32{
	0, // 0: habridge.GetStateResponse.button_state:type_name -> habridge.GetStateResponse.ButtonState
	1, // 1: habridge.GetStateResponse.user_state:type_name -> habridge.GetStateResponse.UserState
	2, // 2: habridge.HabridgeService.GetState:input_type -> habridge.GetStateRequest
	3, // 3: habridge.HabridgeService.GetState:output_type -> habridge.GetStateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_habridge_proto_init() }
func file_habridge_proto_init() {
	if File_habridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_habridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_habridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_habridge_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_habridge_proto_goTypes,
		DependencyIndexes: file_habridge_proto_depIdxs,
		EnumInfos:         file_habridge_proto_enumTypes,
		MessageInfos:      file_habridge_proto_msgTypes,
	}.Build()
	File_habridge_proto = out.File
	file_habridge_proto_rawDesc = nil
	file_habridge_proto_goTypes = nil
	file_habridge_proto_depIdxs = nil
}
