// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: habridge.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HabridgeService_GetState_FullMethodName = "/habridge.HabridgeService/GetState"
)

// HabridgeServiceClient is the client API for HabridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HabridgeServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
}

type habridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHabridgeServiceClient(cc grpc.ClientConnInterface) HabridgeServiceClient {
	return &habridgeServiceClient{cc}
}

func (c *habridgeServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, HabridgeService_GetState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HabridgeServiceServer is the server API for HabridgeService service.
// All implementations should embed UnimplementedHabridgeServiceServer
// for forward compatibility
type HabridgeServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
}

// UnimplementedHabridgeServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHabridgeServiceServer struct {
}

func (UnimplementedHabridgeServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}

// UnsafeHabridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HabridgeServiceServer will
// result in compilation errors.
type UnsafeHabridgeServiceServer interface {
	mustEmbedUnimplementedHabridgeServiceServer()
}

func RegisterHabridgeServiceServer(s grpc.ServiceRegistrar, srv HabridgeServiceServer) {
	s.RegisterService(&HabridgeService_ServiceDesc, srv)
}

func _HabridgeService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabridgeServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabridgeService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabridgeServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HabridgeService_ServiceDesc is the grpc.ServiceDesc for HabridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HabridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "habridge.HabridgeService",
	HandlerType: (*HabridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _HabridgeService_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "habridge.proto",
}
